repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
        name: Ensure newline at end of file
        description: Ensure that files end with a newline
        exclude: |
          (?x)^(
            stacks/.* |
            atlas/.*\.sql$
          )$
      - id: check-yaml
        name: Validate YAML
        description: Ensures YAML is parseable and formatted correctly
#        exclude: |
#          (?x)^(
#            stacks/.* |
#            atlas/.*\.sql$
#          )$
      - id: trailing-whitespace
        name: Remove trailing whitespaces
        description: Removes trailing whitespace
        exclude: |
          (?x)^(
            clusters/.*\.yaml$
          )$
      - id: no-commit-to-branch
        name: Prevent commits to main branch
        description: Stop accidental commits to main
        args: ['--branch', 'main', '--branch', 'master']
  - repo: local
    hooks:
      - id: terramate-fmt
        name: Terramate format
        description: Run terramate fmt to format Terramate-managed files
        entry: terramate
        args: [ "fmt" ]
        language: system
        pass_filenames: false
      - id: terramate-generate
        name: Terramate generate
        description: Run terramate generate to ensure all yaml artifacts are generated
        entry: terramate
        args: [ "generate" ]
        language: system
        pass_filenames: false
